platform :ios, '12.1'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

pod 'Firebase/Core', '~> 6.13.0'
pod 'Firebase/Messaging', '~> 6.13.0'
pod 'Firebase/Auth', '~> 6.13.0'
pod 'Firebase/Firestore', '~> 6.13.0'
pod 'Firebase/Storage', '~> 6.13.0'
# pod 'Firebase/Analytics', '~> 6.13.0'

# pod 'FBSDKCoreKit', '5.8.0'
# pod 'FBSDKLoginKit', '5.8.0'
# pod 'FBSDKShareKit', '5.8.0'

target 'ListingApp' do
  # Pods for ListingApp
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', path: rn_maps_path
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
  pod 'ReactNativeDarkMode', :path => '../node_modules/react-native-dark-mode'
  pod 'toolbar-android', :path=> '../node_modules/@react-native-community/toolbar-android'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  # pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => rn_maps_path
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'
  # use_native_modules!
  pod 'react-native-google-maps', :path => rn_maps_path
  # pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
#   rn_maps_path = '../node_modules/react-native-maps'
# pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

 

# end


# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-google-maps'
#       target.build_configurations.each do |config|
#         # config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#         # config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
#         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#       end

     
#     end
#   end

#   post_install do |installer|
#     ## Fix for XCode 12.5 beta
#     find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
#     "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
# end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

  ## Fix for XCode 12.5
  find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
  "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
  find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
  "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
end
  
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end


